version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: my-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ali
      MONGO_INITDB_ROOT_PASSWORD: hamza
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0
    container_name: my-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ali
      ME_CONFIG_MONGODB_ADMINPASSWORD: hamza
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ali
      ME_CONFIG_BASICAUTH_PASSWORD: hamza

volumes:
  mongo-data:
